# Generated by Django 3.0.7 on 2020-08-09 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200809_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='published',
            new_name='publish',
        ),
    ]
