version: '3.8'

services:
  web:
    env_file:
      - ./prosjekttorg.env
    build: .
    command: gunicorn prosjekttorg.wsgi -b 0.0.0.0:8000
    environment:
      - ENVIRONMENT=production
      - DEBUG=0
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
